<?php

namespace AppBundle\Repository;

/**
 * HangmanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HangmanRepository extends \Doctrine\ORM\EntityRepository
{
}
